apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
    type: app1

spec:
  template:
    metadata:
      name: app1-pod
      labels:
        name: app1-pod
        type: app1-pod
    spec:
      containers:
      - name: app1-container
        image: amiss/app1:v1
        ports:
        - containerPort: 3000
  replicas: 1
  selector:
    matchLabels:
      type: app1-pod
