apiVersion: v1
kind: Service
metadata:
  name: app1-service

spec:
  type: NodePort
  ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30000
  selector:
    name: app1-pod
    type: app1-pod
  
